function [data_out] = xsens_import_process(filename)

%load data
[data] = load_mvnx(sprintf('%s', filename)); 
%% load segment data 

COM = {data.frame.centerOfMass}.';
COM = horzcat(COM{:}); 
COM = COM(3,:)'; 

data_out = struct('pelvis', struct('roll', rad2deg(data.segmentData(1).orientation(:,2)), ...
    'pitch', rad2deg(data.segmentData(1).orientation(:,3)), ...
    'yaw', rad2deg(data.segmentData(1).orientation(:,4)), ...
    'x_pos', rad2deg(data.segmentData(1).position(:,1)),...
    'y_pos', rad2deg(data.segmentData(1).position(:,2)), ...
    'z_pos', rad2deg(data.segmentData(1).position(:,3))),... 
    'trunk', struct('roll', rad2deg(data.segmentData(4).orientation(:,2)), ...
    'pitch', rad2deg(data.segmentData(4).orientation(:,3)), ...
    'yaw', rad2deg(data.segmentData(4).orientation(:,4)), ...
    'x_pos', rad2deg(data.segmentData(4).position(:,1)),...
    'y_pos', rad2deg(data.segmentData(4).position(:,2)), ...
    'z_pos', rad2deg(data.segmentData(4).position(:,3))),...
    'l_hip', struct('abad', data.jointData(19).jointAngle(:,1), ...
    'ext', data.jointData(19).jointAngle(:,2), ...
    'fe', data.jointData(19).jointAngle(:,3)),...
    'l_knee', struct('abad', data.jointData(20).jointAngle(:,1), ...
    'ext', data.jointData(20).jointAngle(:,2), ...
    'fe', data.jointData(20).jointAngle(:,3)),...
    'l_ankle', struct('abad', data.jointData(21).jointAngle(:,1), ...
    'ext', data.jointData(21).jointAngle(:,2), ...
    'fe', data.jointData(21).jointAngle(:,3)),...
    'r_hip', struct('abad', data.jointData(15).jointAngle(:,1), ...
    'ext', data.jointData(15).jointAngle(:,2), ...
    'fe', data.jointData(15).jointAngle(:,3)),...
    'r_knee', struct('abad', data.jointData(16).jointAngle(:,1), ...
    'ext', data.jointData(16).jointAngle(:,2), ...
    'fe', data.jointData(16).jointAngle(:,3)),...
    'r_ankle', struct('abad', data.jointData(17).jointAngle(:,1), ...
    'ext', data.jointData(17).jointAngle(:,2), ...
    'fe', data.jointData(17).jointAngle(:,3)),...
    'l_upper_leg', struct('x_pos', data.segmentData(20).position(:,1),...
    'y_pos', data.segmentData(20).position(:,2),...
    'z_pos', data.segmentData(20).position(:,3)),...
    'l_lower_leg', struct('x_pos', data.segmentData(21).position(:,1),...
    'y_pos', data.segmentData(21).position(:,2),...
    'z_pos', data.segmentData(21).position(:,3)),...    
    'r_upper_leg', struct('x_pos', data.segmentData(16).position(:,1),...
    'y_pos', data.segmentData(16).position(:,2),...
    'z_pos', data.segmentData(16).position(:,3)),...
    'r_lower_leg', struct('x_pos', data.segmentData(17).position(:,1),...
    'y_pos', data.segmentData(17).position(:,2),...
    'z_pos', data.segmentData(17).position(:,3)),...
    'l_foot', struct('x_pos', data.segmentData(22).position(:,1),...
    'y_pos', data.segmentData(22).position(:,2),...
    'z_pos', data.segmentData(22).position(:,3)),...
    'r_foot', struct('x_pos', data.segmentData(18).position(:,1),...
    'y_pos', data.segmentData(18).position(:,2),...
    'z_pos', data.segmentData(18).position(:,3)),...
    'COM', COM,...
    'footContact', data.footContact,...
    'frame', data.frame);


end

